spring:
    application:
        name: pesquisasSalariais
    profiles: 
        active: memoryTokenStorage
    mail:
        host: localhost
        port: 25
        username:
        password:
    datasource:
        driver-class-name: org.postgresql.ds.PGPoolingDataSource
        url: jdbc:postgresql://localhost/postgres
        name: default
        username: postgres
        password: postgres
        initialConnections: 5
        maxConnections: 15
    jpa:
        generate-ddl: true
        open-in-view: false
        database-platform: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql:  true
        properties:
            hibernate.cache.use_second_level_cache: true
            hibernate.cache.use_query_cache: false
            hibernate.generate_statistics: false
            hibernate.cache.region.factory_class: org.hibernate.cache.ehcache.SingletonEhCacheRegionFactory
            hibernate.format_sql: true
            hibernate.show_sql: true
            hibernate.default_schema: salarial
            hibernate.discriminator.ignore_explicit_for_joined: true
    batch:
        initializer:
            enabled: false
        job:
            enabled: false
    redis:
        host: 10.27.68.92
management:
    context-path: /admin
    port:  9090        
endpoints:
    health:
        id: health
        enabled: true
        sensitive: true
server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css, application/javascript, application/json
        
applicationProperties:
    security:
        authentication:
            oauth:
                clientid: pesquisasSalariais
                secret:  pesquisasSalariais
    mail:
        from: teste2@localhost
    cors: 
        allowed-origins: "*"
        allowed-methods: GET, PUT, POST, DELETE
        allowed-headers: "*"
        exposed-headers: "X-Validation-Error, X-Business-Error, X-Total-Count" 
        allow-credentials: true
        max-age: 1800
    async:
        corePoolSize: 2
        maxPoolSize: 50
        queueCapacity: 10000        
    cache: 
        timeToLiveSeconds: 3600
        ehcache:
            maxBytesLocalHeap: 64M
    metrics: 
        jmx.enabled: false
        spark:
            enabled: false
            host: localhost
            port: 9999
        graphite:
            enabled: false
            host: localhost
            port: 2003
            prefix: teste2
                